apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app-deployment
  labels: 
    app: two-tier-app

spec:
  replicas: 4
  selector: 
    matchLabels:
      app: two-tier-app

  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app-ctr
          image: abd126/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.104.40.237"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "myDb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always    
